name: push on release

on:
  push:
    branches:
      - "release/*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Trigger manually deployment
    runs-on: ubuntu-latest
    steps:
      - name: Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6.4
      - name: Show vars
        run: |
          echo "${{ github.ref }}"
          echo "${{ steps.branch-name.outputs.current_branch }}"
          echo "${{ steps.branch-name.outputs.current_branch }}"
          echo "${{ steps.branch-name.outputs.current_branch }}"
