name: push on release

on:
  push:
    branches:
      - "release/*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Trigger manually deployment
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        # run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Show vars
        run: |
          echo "${{ steps.extract_branch.outputs.branch }}"
          echo "${{ github.ref }}"
          echo "${{ github.head_ref }}"
